# Generated by Django 5.1.3 on 2025-02-04 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_clientaddressmaster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientaddressmaster",
            name="area",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="clientaddressmaster",
            name="flat_building",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="clientaddressmaster",
            name="pincode",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{6}$", message="Enter a valid 6-digit pincode."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="clientaddressmaster",
            name="street",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="clientmobilenumbermaster",
            name="mobile_number",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
