services:
  docs:
    image: crm_local_docs
    container_name: crm_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./crm:/app/crm:z
    ports:
      - '9000:9000'
    command: /start-docs
