# Generated by Django 5.0.8 on 2025-02-14 06:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_alter_organizationmaster_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBodyMeasurementMaster',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('activity_level', models.CharField(blank=True, max_length=255, null=True)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('extra_comments', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientMaster',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('is_lead', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationmaster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientEmailMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='clients.clientmaster')),
            ],
        ),
        migrations.CreateModel(
            name='ClientBodyStatusMaster',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ideal_body_weight', models.FloatField(blank=True, help_text='Ideal weight in kg', null=True)),
                ('over_under_weight', models.FloatField(blank=True, help_text='Difference from ideal weight in kg', null=True)),
                ('fat_percentage', models.FloatField(blank=True, help_text='Body fat percentage', null=True)),
                ('lbm_percentage', models.FloatField(blank=True, help_text='Lean body mass percentage', null=True)),
                ('lbm_kg', models.FloatField(blank=True, help_text='Lean body mass in kg', null=True)),
                ('protein_required', models.FloatField(blank=True, help_text='Protein required in grams/kg', null=True)),
                ('total_protein_required', models.FloatField(blank=True, help_text='Total protein required in grams', null=True)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('activity_level', models.CharField(blank=True, choices=[('Sedentary', 'Sedentary'), ('Lightly Active', 'Lightly Active'), ('Moderately Active', 'Moderately Active'), ('Very Active', 'Very Active')], max_length=50, null=True)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('extra_comments', models.TextField(blank=True, null=True)),
                ('body_measurements', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.clientbodymeasurementmaster')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_statuses', to='clients.clientmaster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clientbodymeasurementmaster',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_measurements', to='clients.clientmaster'),
        ),
        migrations.CreateModel(
            name='ClientAddressMaster',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flat_building', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='Enter a valid 6-digit pincode.')])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='clients.clientmaster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientMobileNumberMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_numbers', to='clients.clientmaster')),
            ],
        ),
    ]
