# Generated by Django 5.0.8 on 2024-08-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationmaster_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmaster',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
