# Generated by Django 5.0.12 on 2026-04-29 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organizationmaster_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationaddressmaster',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='organizations.organizationmaster'),
        ),
        migrations.AlterField(
            model_name='organizationemailmaster',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to='organizations.organizationmaster'),
        ),
        migrations.AlterField(
            model_name='organizationmobilenumbermaster',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_numbers', to='organizations.organizationmaster'),
        ),
    ]
