import { describe, it, expect } from 'vitest'
import { renderInvoiceDocument } from '../../../src/main/pdf/templates/invoice-document'
import { renderPaymentReceipt } from '../../../src/main/pdf/templates/payment-receipt'
import type { InvoicePrintContext, ReceiptPrintContext } from '../../../src/main/pdf/types'

describe('Invoice Document Template', () => {
  const baseCtx: InvoicePrintContext = {
    org: {
      name: 'Test Gym',
      legalName: 'Test Gym Pvt Ltd',
      logo: null,
      address: '123 Main St, Mumbai',
      gstin: '27AABCU9603R1ZM',
      mobileNumber: '9876543210',
      invoicePrefix: 'GYM'
    },
    invoiceNo: 'GYM-290826-01',
    status: 'PAID',
    issuedAt: '2026-08-29T10:00:00Z',
    dueAt: null,
    customer: {
      name: 'Viren',
      phone: '9876543210',
      email: 'viren@test.com'
    },
    billingSnapshot: null,
    lines: [
      {
        description: 'Gold Plan (12 months)',
        quantity: 1,
        unitPrice: 2000000,
        taxRate: 18,
        discountAmount: 0,
        lineTotal: 2000000
      }
    ],
    subtotal: 2000000,
    taxTotal: 360000,
    total: 2360000,
    allocations: [
      {
        paymentNo: 'PAY-0001',
        method: 'CASH',
        amount: 1500000,
        receivedAt: '2026-08-29T10:30:00Z'
      },
      {
        paymentNo: 'PAY-0002',
        method: 'UPI',
        amount: 860000,
        receivedAt: '2026-08-29T11:00:00Z'
      }
    ],
    paidAmount: 2360000,
    outstanding: 0,
    generatedAt: '29 Aug 2026, 12:00 PM'
  }

  it('renders valid HTML document', () => {
    const html = renderInvoiceDocument(baseCtx)
    expect(html).toContain('<!DOCTYPE html>')
    expect(html).toContain('<html>')
    expect(html).toContain('</html>')
  })

  it('includes org name in header', () => {
    const html = renderInvoiceDocument(baseCtx)
    expect(html).toContain('Test Gym')
  })

  it('skips logo when null', () => {
    const html = renderInvoiceDocument(baseCtx)
    expect(html).not.toContain('<img')
  })

  it('renders logo when provided', () => {
    const ctx = {
      ...baseCtx,
      org: { ...baseCtx.org, logo: 'https://example.com/logo.png' }
    }
    const html = renderInvoiceDocument(ctx)
    expect(html).toContain('<img')
    expect(html).toContain('header-logo')
    expect(html).toContain('https://example.com/logo.png')
  })

  it('includes invoice number', () => {
    const html = renderInvoiceDocument(baseCtx)
    expect(html).toContain('GYM-290826-01')
  })

  it('includes customer name', () => {
    const html = renderInvoiceDocument(baseCtx)
    expect(html).toContain('Viren')
  })

  it('includes line item description', () => {
    const html = renderInvoiceDocument(baseCtx)
    expect(html).toContain('Gold Plan (12 months)')
  })

  it('renders allocations table', () => {
    const html = renderInvoiceDocument(baseCtx)
    expect(html).toContain('PAY-0001')
    expect(html).toContain('PAY-0002')
    expect(html).toContain('CASH')
    expect(html).toContain('UPI')
  })

  it('shows amounts in rupees (paise / 100)', () => {
    const html = renderInvoiceDocument(baseCtx)
    // 2000000 paise = ₹ 20,000
    expect(html).toContain('₹ 20,000')
    // 360000 paise = ₹ 3,600
    expect(html).toContain('₹ 3,600')
    // 2360000 paise = ₹ 23,600
    expect(html).toContain('₹ 23,600')
  })

  it('shows outstanding as zero when fully paid', () => {
    const html = renderInvoiceDocument(baseCtx)
    expect(html).toContain('Outstanding')
    expect(html).toContain('₹ 0')
  })

  it('shows outstanding when partially paid', () => {
    const ctx = {
      ...baseCtx,
      paidAmount: 1500000,
      outstanding: 860000,
      allocations: [baseCtx.allocations[0]]
    }
    const html = renderInvoiceDocument(ctx)
    expect(html).toContain('₹ 8,600')
  })

  it('shows no-payments message when allocations empty', () => {
    const ctx = {
      ...baseCtx,
      allocations: [],
      paidAmount: 0,
      outstanding: 2360000
    }
    const html = renderInvoiceDocument(ctx)
    expect(html).toContain('No payments recorded')
  })

  it('includes GSTIN when provided', () => {
    const html = renderInvoiceDocument(baseCtx)
    expect(html).toContain('GSTIN: 27AABCU9603R1ZM')
  })

  it('excludes GSTIN when not provided', () => {
    const ctx = {
      ...baseCtx,
      org: { ...baseCtx.org, gstin: null }
    }
    const html = renderInvoiceDocument(ctx)
    expect(html).not.toContain('GSTIN')
  })

  it('includes footer with generation timestamp', () => {
    const html = renderInvoiceDocument(baseCtx)
    expect(html).toContain('Generated by CrownCRM')
    expect(html).toContain('29 Aug 2026, 12:00 PM')
  })

  it('includes discount note when discount > 0', () => {
    const ctx = {
      ...baseCtx,
      lines: [
        { ...baseCtx.lines[0], discountAmount: 200000 }
      ]
    }
    const html = renderInvoiceDocument(ctx)
    expect(html).toContain('Discount')
    expect(html).toContain('₹ 2,000')
  })

  it('includes accent bar', () => {
    const html = renderInvoiceDocument(baseCtx)
    expect(html).toContain('accent-bar')
    expect(html).toContain('linear-gradient')
  })

  it('includes grand total in dark box', () => {
    const html = renderInvoiceDocument(baseCtx)
    expect(html).toContain('totals-row grand')
    expect(html).toContain('#111827')
  })
})

describe('Payment Receipt Template', () => {
  const baseCtx: ReceiptPrintContext = {
    org: {
      name: 'Test Gym',
      logo: null,
      address: '123 Main St, Mumbai',
      gstin: null,
      mobileNumber: '9876543210'
    },
    paymentNo: 'PAY-0001',
    paymentDate: '2026-08-29',
    amount: 1500000,
    method: 'CASH',
    reference: null,
    customer: {
      name: 'Viren',
      phone: '9876543210',
      email: null
    },
    allocations: [
      { invoiceNo: 'GYM-290826-01', amount: 1500000 }
    ],
    receivedBy: 'John',
    generatedAt: '29 Aug 2026, 12:00 PM'
  }

  it('renders valid HTML document', () => {
    const html = renderPaymentReceipt(baseCtx)
    expect(html).toContain('<!DOCTYPE html>')
    expect(html).toContain('<html>')
    expect(html).toContain('</html>')
  })

  it('includes payment number', () => {
    const html = renderPaymentReceipt(baseCtx)
    expect(html).toContain('PAY-0001')
  })

  it('includes customer name', () => {
    const html = renderPaymentReceipt(baseCtx)
    expect(html).toContain('Viren')
  })

  it('shows amount in rupees (paise / 100)', () => {
    const html = renderPaymentReceipt(baseCtx)
    // 1500000 paise = ₹ 15,000
    expect(html).toContain('₹ 15,000')
  })

  it('includes payment method', () => {
    const html = renderPaymentReceipt(baseCtx)
    expect(html).toContain('Cash')
  })

  it('renders allocation to invoice', () => {
    const html = renderPaymentReceipt(baseCtx)
    expect(html).toContain('GYM-290826-01')
  })

  it('shows unallocated notice when no allocations', () => {
    const ctx = {
      ...baseCtx,
      allocations: []
    }
    const html = renderPaymentReceipt(ctx)
    expect(html).toContain('not been allocated')
    expect(html).toContain('⚠')
  })

  it('hides allocations table when unallocated', () => {
    const ctx = {
      ...baseCtx,
      allocations: []
    }
    const html = renderPaymentReceipt(ctx)
    expect(html).not.toContain('<table>')
  })

  it('includes received by name', () => {
    const html = renderPaymentReceipt(baseCtx)
    expect(html).toContain('John')
  })

  it('includes footer', () => {
    const html = renderPaymentReceipt(baseCtx)
    expect(html).toContain('Generated by CrownCRM')
  })

  it('includes org address when provided', () => {
    const html = renderPaymentReceipt(baseCtx)
    expect(html).toContain('123 Main St, Mumbai')
  })

  it('excludes org address when not provided', () => {
    const ctx = {
      ...baseCtx,
      org: { ...baseCtx.org, address: null }
    }
    const html = renderPaymentReceipt(ctx)
    expect(html).not.toContain('123 Main St')
  })

  it('includes payment hero card', () => {
    const html = renderPaymentReceipt(baseCtx)
    expect(html).toContain('Payment Received')
    expect(html).toContain('background: #ECFDF5')
  })

  it('includes accent bar', () => {
    const html = renderPaymentReceipt(baseCtx)
    expect(html).toContain('accent-bar')
  })
})
