# Generated by Django 5.0.12 on 2025-06-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_leademailaddressmaster_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmaster',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('INTERESTED', 'Interested'), ('CONVERTED', 'Converted'), ('DROPPED', 'Dropped')], default='NEW', help_text='Current status of the lead', max_length=15),
        ),
    ]
