# Generated by Django 5.0.12 on 2025-07-08 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_leadmaster_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leademailaddressmaster',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='leadmobilenumbermaster',
            name='mobile_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Enter a valid 10-digit mobile number.')]),
        ),
    ]
