# Generated by Django 5.0.12 on 2026-04-29 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_leademailaddressmaster_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(help_text='When to follow up')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('social', 'Social Media'), ('in_person', 'In Person')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('outcome', models.TextField(blank=True, help_text='What happened during the follow-up?', null=True)),
                ('notes', models.TextField(blank=True, help_text="CRM user's personal observations", null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='leads.leadmaster')),
            ],
            options={
                'verbose_name': 'Lead Follow-Up',
                'verbose_name_plural': 'Lead Follow-Ups',
                'ordering': ['-scheduled_for'],
            },
        ),
    ]
