# Generated by Django 5.2.13 on 2026-05-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_leadmaster_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='leadmaster',
            managers=[
            ],
        ),
    ]
