# Generated by Django 5.0.12 on 2025-06-08 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('logistics', '0001_initial'),
        ('organizations', '0003_alter_organizationmaster_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='logistics.order'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_transactions', to='accounting.accountledger'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_transactions', to='accounting.bill'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_transactions', to='organizations.organizationmaster'),
        ),
    ]
