# Generated by Django 5.0.12 on 2025-06-20 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_membertype_code_alter_membertype_description'),
        ('organizations', '0003_alter_organizationmaster_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationmaster'),
        ),
        migrations.AddField(
            model_name='membershipsale',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationmaster'),
        ),
        migrations.AddField(
            model_name='membertype',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationmaster'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationmaster'),
        ),
    ]
