# Generated by Django 5.0.12 on 2025-06-21 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_membershipplan_organization_and_more'),
        ('leads', '0003_leadmaster_status'),
        ('organizations', '0003_alter_organizationmaster_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplan',
            name='duration',
        ),
        migrations.AddField(
            model_name='membershipsale',
            name='custom_diet_plans',
            field=models.PositiveIntegerField(blank=True, help_text='Custom diet plans (overrides plan default)', null=True),
        ),
        migrations.AddField(
            model_name='membershipsale',
            name='custom_duration',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('6months', '6 Months'), ('yearly', 'Yearly')], help_text='Custom duration (overrides plan default)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='membershipsale',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom price (overrides plan default)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membershipsale',
            name='custom_pt_sessions',
            field=models.PositiveIntegerField(blank=True, help_text='Custom PT sessions (overrides plan default)', null=True),
        ),
        migrations.AddField(
            model_name='membershipsale',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated discount percentage from standard price', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='membershipsale',
            name='duration',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('6months', '6 Months'), ('yearly', 'Yearly')], default='YEARLY', help_text='Selected duration for this membership', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipsale',
            name='is_customized',
            field=models.BooleanField(default=False, help_text='Whether any plan details were customized'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationmaster'),
        ),
        migrations.AlterField(
            model_name='membershipsale',
            name='date_created',
            field=models.DateField(auto_now_add=True, help_text='Date when the sale was created'),
        ),
        migrations.AlterField(
            model_name='membershipsale',
            name='decided_amount',
            field=models.DecimalField(decimal_places=2, help_text='Final agreed amount for this sale', max_digits=10),
        ),
        migrations.AlterField(
            model_name='membershipsale',
            name='lead',
            field=models.ForeignKey(help_text='The lead who purchased the membership', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='leads.leadmaster'),
        ),
        migrations.AlterField(
            model_name='membershipsale',
            name='membership_type',
            field=models.ForeignKey(help_text='Type of membership (e.g., Gold, Platinum)', on_delete=django.db.models.deletion.PROTECT, to='accounting.membertype'),
        ),
        migrations.AlterField(
            model_name='membershipsale',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the sale', null=True),
        ),
        migrations.AlterField(
            model_name='membershipsale',
            name='organization',
            field=models.ForeignKey(help_text='Organization this sale belongs to', on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationmaster'),
        ),
        migrations.AlterField(
            model_name='membershipsale',
            name='plan',
            field=models.ForeignKey(help_text='The standard membership plan being sold', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='accounting.membershipplan'),
        ),
        migrations.AlterField(
            model_name='membertype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationmaster'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationmaster'),
        ),
    ]
