# Generated by Django 5.0.12 on 2025-06-27 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_remove_membershipplan_duration_and_more'),
        ('organizations', '0003_alter_organizationmaster_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipsale',
            name='date_created',
        ),
        migrations.AddField(
            model_name='membershipsale',
            name='membership_start_date',
            field=models.DateField(blank=True, help_text='Date when the membership of the lead starts, Helps track membership validity.', null=True),
        ),
        migrations.AlterField(
            model_name='membershipsale',
            name='membership_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.membertype'),
        ),
        migrations.AlterField(
            model_name='membershipsale',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationmaster'),
        ),
        migrations.AlterField(
            model_name='membershipsale',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='accounting.membershipplan'),
        ),
    ]
