# Generated by Django 5.0.12 on 2025-06-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_remove_membershipsale_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipsale',
            name='membership_type',
        ),
    ]
