# Generated by Django 5.0.12 on 2025-07-01 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_remove_membershipsale_membership_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipsale',
            name='decided_amount',
        ),
        migrations.RemoveField(
            model_name='membershipsale',
            name='is_customized',
        ),
    ]
