# Generated by Django 5.0.12 on 2025-07-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_remove_membershipsale_decided_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
