# Generated by Django 5.0.12 on 2025-07-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_paymentreceipt_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceipt',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
