# Generated by Django 5.0.12 on 2025-07-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_paymentreceipt_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipsale',
            name='membership_end_date',
            field=models.DateField(blank=True, help_text='Date when the membership of the lead ends.', null=True),
        ),
    ]
