# Generated by Django 5.0.12 on 2025-07-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_membershipsale_membership_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipsale',
            name='membership_end_date',
        ),
    ]
