# Generated by Django 5.0.12 on 2026-04-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_remove_membershipsale_membership_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipsale',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='membertype',
            name='organization',
        ),
        migrations.RenameField(
            model_name='membershipsale',
            old_name='custom_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='membershipsale',
            name='custom_diet_plans',
        ),
        migrations.RemoveField(
            model_name='membershipsale',
            name='custom_duration',
        ),
        migrations.RemoveField(
            model_name='membershipsale',
            name='custom_pt_sessions',
        ),
        migrations.AddField(
            model_name='membershipsale',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price of the plan', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membershipsale',
            name='membership_end_date',
            field=models.DateField(blank=True, help_text="Membership expiration date. For preset durations, auto-computed via JS. For 'Custom' duration, enter manually.", null=True),
        ),
        migrations.AlterField(
            model_name='membershipsale',
            name='duration',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('6months', '6 Months'), ('yearly', 'Yearly'), ('custom', 'custom')], help_text='Selected duration for this membership', max_length=20),
        ),
        migrations.DeleteModel(
            name='MembershipPlan',
        ),
        migrations.DeleteModel(
            name='MemberType',
        ),
    ]
