# Generated by Django 5.2.13 on 2026-05-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_add_membership_end_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/pdfs/'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='pdf_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', max_length=20),
        ),
    ]
