# Generated by Django 5.2.13 on 2026-05-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_alter_membershipsale_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='membershipsale',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='paymentreceipt',
            managers=[
            ],
        ),
    ]
