# Generated by Django 5.0.12 on 2025-06-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_categorysp_remove_service_category_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsn',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
