# Generated by Django 5.0.12 on 2025-06-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_product_hsn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='price_at_purchase',
            new_name='price',
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this service is currently available'),
        ),
        migrations.AddField(
            model_name='service',
            name='notes',
            field=models.TextField(blank=True, help_text='Any additional notes or remarks about the service', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(help_text='Unique identifier for this service', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(blank=True, help_text='Duration of the service (if applicable)', null=True),
        ),
    ]
