# Generated by Django 5.0.12 on 2025-06-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='logistics.categorysp'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ManyToManyField(blank=True, to='logistics.categorysp'),
        ),
    ]
