# Generated by Django 5.0.12 on 2025-06-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_alter_product_category_alter_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='service',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='service',
            name='notes',
        ),
        migrations.AddField(
            model_name='service',
            name='sessions_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of sessions (if type is sessions)', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('6_months', '6 Months'), ('yearly', 'Yearly')], help_text='Subscription duration (if type is subscription)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('sessions', 'Sessions'), ('subscription', 'Subscription')], default='sessions', help_text='Type of service: sessions or subscription.', max_length=20),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderLineItem',
        ),
    ]
