import { DatabaseSync } from 'node:sqlite'
import { getDb, withTransaction } from './connection'
import identitySql from './migrations/20260817133412_identity/migration.sql?raw'
import salesSql from './migrations/20260817145915_sales/migration.sql?raw'
import salesListIndexSql from './migrations/20260818035220_sales_list_index/migration.sql?raw'
import leadsExtraFieldsSql from './migrations/20260818051253_leads_extra_fields/migration.sql?raw'
import seedSalesReferenceDataSql from './migrations/20260819100000_seed_sales_reference_data/migration.sql?raw'
import grantLeadDeleteSql from './migrations/20260819120000_grant_lead_delete/migration.sql?raw'
import grantLeadEditSql from './migrations/20260819140000_grant_lead_edit/migration.sql?raw'
import catalogPlansSql from './migrations/20260820053730_catalog_plans/migration.sql?raw'
import seedPlansSql from './migrations/20260820060000_seed_plans/migration.sql?raw'
import catalogOffersPoliciesSql from './migrations/20260820133254_catalog_offers_policies/migration.sql?raw'
import seedCatalogPoliciesSql from './migrations/20260820140000_seed_catalog_policies/migration.sql?raw'
import offerVersionsSql from './migrations/20260821120000_offer_versions/migration.sql?raw'
import followupEditCancelSql from './migrations/20260821150000_followup_edit_cancel/migration.sql?raw'
import customersMembershipsBillingFinanceSql from './migrations/20260821080624_good_may_parker/migration.sql?raw'
import membershipSaleIdempotencySql from './migrations/20260823150000_membership_sale_idempotency/migration.sql?raw'
import membershipSellPermissionSql from './migrations/20260823160000_membership_sell_permission/migration.sql?raw'
import membershipJoiningDateSql from './migrations/20260826180000_membership_joining_date/migration.sql?raw'
import orgBrandingSql from './migrations/20260830120000_org_branding/migration.sql?raw'
import followupNotesSql from './migrations/20260831120000_followup_notes/migration.sql?raw'
import followupCancelReasonSql from './migrations/20260901120000_followup_cancel_reason/migration.sql?raw'
import suppressFollowupsSql from './migrations/20260902120000_lead_stage_suppress_followups/migration.sql?raw'
import planAvailabilitySql from './migrations/20260903120000_plan_availability/migration.sql?raw'
import personBlacklistSql from './migrations/20260903120000_person_blacklist/migration.sql?raw'
import personPhotoSql from './migrations/20260903120000_person_photo/migration.sql?raw'
import seedDndNotInterestedSql from './migrations/20260904120000_seed_dnd_not_interested/migration.sql?raw'

/**
 * Migrations are generated by drizzle-kit into `src/main/db/migrations/` and
 * bundled into the main-process bundle via Vite `?raw` imports (no `.sql` files
 * to copy alongside the packaged app). Each runs once, tracked by version in
 * the `schema_migrations` table (same semantics as the shipped runner).
 *
 * Version 0 is the drizzle-generated identity baseline. Existing databases that
 * predate the Drizzle retrofit carry versions 1 (`identity_tenancy`) and 2
 * (`app_meta`) in `schema_migrations` — their tables are already present, so
 * version 0 is marked applied instead of re-executed. New Drizzle migrations
 * must therefore start at version 3 and up: versions 1 and 2 are permanently
 * reserved by the legacy runner, otherwise a legacy database would skip a new
 * migration that shares a legacy version number.
 */
const migrations: Migration[] = [
  { version: 0, name: 'identity', sql: identitySql },
  { version: 3, name: 'sales', sql: salesSql },
  { version: 4, name: 'sales_list_index', sql: salesListIndexSql },
  { version: 5, name: 'leads_extra_fields', sql: leadsExtraFieldsSql },
  { version: 6, name: 'seed_sales_reference_data', sql: seedSalesReferenceDataSql },
  { version: 7, name: 'grant_lead_delete', sql: grantLeadDeleteSql },
  { version: 8, name: 'grant_lead_edit', sql: grantLeadEditSql },
  { version: 9, name: 'catalog_plans', sql: catalogPlansSql },
  { version: 10, name: 'seed_plans', sql: seedPlansSql },
  { version: 11, name: 'catalog_offers_policies', sql: catalogOffersPoliciesSql },
  { version: 12, name: 'seed_catalog_policies', sql: seedCatalogPoliciesSql },
  { version: 13, name: 'offer_versions', sql: offerVersionsSql },
  { version: 14, name: 'followup_edit_cancel', sql: followupEditCancelSql },
  {
    version: 15,
    name: 'customers_memberships_billing_finance',
    sql: customersMembershipsBillingFinanceSql
  },
  { version: 16, name: 'membership_sale_idempotency', sql: membershipSaleIdempotencySql },
  { version: 17, name: 'membership_sell_permission', sql: membershipSellPermissionSql },
  { version: 18, name: 'membership_joining_date', sql: membershipJoiningDateSql },
  { version: 19, name: 'org_branding', sql: orgBrandingSql },
  { version: 20, name: 'followup_notes', sql: followupNotesSql },
  { version: 21, name: 'followup_cancel_reason', sql: followupCancelReasonSql },
  { version: 22, name: 'lead_stage_suppress_followups', sql: suppressFollowupsSql },
  { version: 23, name: 'plan_availability', sql: planAvailabilitySql },
  { version: 24, name: 'person_blacklist', sql: personBlacklistSql },
  { version: 25, name: 'person_photo', sql: personPhotoSql },
  { version: 26, name: 'seed_dnd_not_interested', sql: seedDndNotInterestedSql }
]

interface Migration {
  version: number
  name: string
  sql: string
}

const BREAKPOINT_RE = /^\s*--> statement-breakpoint\s*$/m

/**
 * Executes a drizzle-kit generated SQL file. The file separates statements with
 * `--> statement-breakpoint` comment markers (not valid SQL), so it is split on
 * those markers and each statement is executed independently — matching how the
 * generated file is laid out.
 */
function applySql(db: DatabaseSync, sql: string): void {
  const statements = sql
    .split(BREAKPOINT_RE)
    .map((s) => s.trim())
    .filter(Boolean)
  for (const statement of statements) {
    db.exec(statement)
  }
}

/**
 * Applies pending migrations in version order, recording each in
 * `schema_migrations` only after it succeeds. The whole run is atomic: a
 * failing migration rolls everything back (SQLite DDL is transactional), so a
 * partially migrated schema is never left behind. Legacy databases created by
 * the pre-Drizzle runner are reconciled by marking version 0 applied without
 * executing it.
 */
export function runMigrations(): void {
  const db: DatabaseSync = getDb()

  withTransaction(() => {
    db.exec(`
      CREATE TABLE IF NOT EXISTS schema_migrations (
        version INTEGER PRIMARY KEY,
        name TEXT NOT NULL,
        applied_at TEXT NOT NULL DEFAULT (datetime('now'))
      );
    `)

    const applied = new Set(
      (db.prepare('SELECT version FROM schema_migrations').all() as { version: number }[]).map(
        (r) => r.version
      )
    )

    if (!applied.has(0)) {
      const hasLegacyTables =
        db
          .prepare(
            `SELECT 1 AS x FROM sqlite_master
             WHERE type = 'table' AND name = 'organizations'`
          )
          .get() !== undefined
      if (hasLegacyTables) {
        db.prepare('INSERT INTO schema_migrations (version, name) VALUES (?, ?)').run(0, 'identity')
        applied.add(0)
      }
    }

    const insert = db.prepare('INSERT INTO schema_migrations (version, name) VALUES (?, ?)')

    for (const migration of migrations) {
      if (applied.has(migration.version)) continue
      applySql(db, migration.sql)
      insert.run(migration.version, migration.name)
    }
  })
}
